#if canImport(Libtailscale)
import Libtailscale
import Foundation
import Security
import os

/// iOS implementation of Go's libtailscale.AppContext interface.
///
/// This class conforms to the protocol generated by `gomobile bind`.
/// The protocol name `LibtailscaleAppContext` follows standard gomobile naming conventions
/// for package `libtailscale`, interface `AppContext`.
///
/// If gomobile generates a different protocol name, adjust the conformance declaration.
///
/// Safe to use in both App and Extension processes (no UIKit dependency).
class GoAppContext: NSObject, LibtailscaleAppContextProtocol {

    private let logger = Logger(subsystem: IPCConstants.appBundleID, category: "go")
    private let keychainGroups = GoAppContext.keychainGroupCandidates()
    private let fallbackPreferences = sharedDefaults ?? UserDefaults.standard

    private static func keychainGroupCandidates(includeLegacy: Bool = false) -> [String?] {
        let baseGroup = IPCConstants.keychainGroupID
        var groups: [String?] = ["TROLLSTORE.\(baseGroup)", nil]
        if includeLegacy {
            groups.insert(contentsOf: [
                baseGroup,
            ], at: 1)
        }
        return groups
    }

    private static func withAccessGroup(_ keychainGroup: String?, query: [String: Any]) -> [String: Any] {
        var query = query
        if let keychainGroup = keychainGroup {
            query[kSecAttrAccessGroup as String] = keychainGroup
        }
        return query
    }

    static func clearPersistedState() {
        let persistentKeys = persistedStateKeys()
        let preferenceStores = [sharedDefaults, UserDefaults.standard].compactMap { $0 }

        for preferences in preferenceStores {
            for key in persistentKeys {
                preferences.removeObject(forKey: key)
            }

            for key in preferences.dictionaryRepresentation().keys where isPersistedStateKey(key) {
                preferences.removeObject(forKey: key)
            }

            preferences.synchronize()
        }

        for keychainGroup in keychainGroupCandidates(includeLegacy: true) {
            for account in persistentKeys {
                let deleteQuery = withAccessGroup(keychainGroup, query: [
                    kSecClass as String: kSecClassGenericPassword,
                    kSecAttrAccount as String: account,
                ])
                SecItemDelete(deleteQuery as CFDictionary)
            }

            let query = withAccessGroup(keychainGroup, query: [
                kSecClass as String: kSecClassGenericPassword,
                kSecReturnAttributes as String: true,
                kSecMatchLimit as String: kSecMatchLimitAll,
            ])

            var result: AnyObject?
            let status = SecItemCopyMatching(query as CFDictionary, &result)
            guard status == errSecSuccess, let items = result as? [[String: Any]] else { continue }

            for item in items {
                guard let account = item[kSecAttrAccount as String] as? String,
                      isPersistedStateKey(account) else { continue }
                let deleteQuery = withAccessGroup(keychainGroup, query: [
                    kSecClass as String: kSecClassGenericPassword,
                    kSecAttrAccount as String: account,
                ])
                SecItemDelete(deleteQuery as CFDictionary)
            }
        }
    }

    private static func persistedStateKeys() -> [String] {
        [
            "privatelogid",
            "statestore-_machinekey",
            "statestore-_profiles",
            "statestore-_current-profile",
            "statestore-_daemon",
        ]
    }

    private static func isPersistedStateKey(_ key: String) -> Bool {
        key.hasPrefix("statestore-") || persistedStateKeys().contains(key)
    }

    // MARK: - Logging

    func log(_ tag: String?, logLine: String?) {
        logger.log("\(tag ?? "go", privacy: .public): \(logLine ?? "", privacy: .public)")
    }

    // MARK: - Encrypted Preferences (Keychain)

    func encrypt(toPref key: String?, value: String?) throws {
        guard let key = key, let value = value else { return }
        let data = Data(value.utf8)
        var lastStatus: OSStatus = errSecSuccess
        var sawMissingEntitlement = false

        for keychainGroup in keychainGroups {
            // Delete existing item first to avoid errSecDuplicateItem
            let deleteQuery = GoAppContext.withAccessGroup(keychainGroup, query: [
                kSecClass as String: kSecClassGenericPassword,
                kSecAttrAccount as String: key,
            ])
            let delStatus = SecItemDelete(deleteQuery as CFDictionary)
            if delStatus != errSecSuccess && delStatus != errSecItemNotFound {
                if delStatus == errSecMissingEntitlement {
                    sawMissingEntitlement = true
                }
                lastStatus = delStatus
                continue
            }

            let addQuery = GoAppContext.withAccessGroup(keychainGroup, query: [
                kSecClass as String: kSecClassGenericPassword,
                kSecAttrAccount as String: key,
                kSecValueData as String: data,
                kSecAttrAccessible as String: kSecAttrAccessibleAfterFirstUnlock,
            ])

            let status = SecItemAdd(addQuery as CFDictionary, nil)
            if status == errSecSuccess {
                fallbackPreferences.set(value, forKey: key)
                return
            }
            if status == errSecMissingEntitlement {
                sawMissingEntitlement = true
            }
            lastStatus = status
        }

        if sawMissingEntitlement {
            fallbackPreferences.set(value, forKey: key)
            return
        }

        throw NSError(domain: NSOSStatusErrorDomain, code: Int(lastStatus))
    }

    func decrypt(fromPref key: String?, error: NSErrorPointer) -> String {
        guard let key = key else { return "" }

        var lastStatus: OSStatus = errSecItemNotFound
        var sawItemNotFound = false
        var sawMissingEntitlement = false

        for keychainGroup in keychainGroups {
            let query = GoAppContext.withAccessGroup(keychainGroup, query: [
                kSecClass as String: kSecClassGenericPassword,
                kSecAttrAccount as String: key,
                kSecReturnData as String: true,
                kSecMatchLimit as String: kSecMatchLimitOne,
            ])

            var result: AnyObject?
            let status = SecItemCopyMatching(query as CFDictionary, &result)
            if status == errSecSuccess, let data = result as? Data {
                let value = String(data: data, encoding: .utf8) ?? ""
                if fallbackPreferences.string(forKey: key) != value {
                    fallbackPreferences.set(value, forKey: key)
                }
                return value
            }
            if status == errSecItemNotFound {
                sawItemNotFound = true
            } else if status == errSecMissingEntitlement {
                sawMissingEntitlement = true
            } else {
                lastStatus = status
            }
        }

        if let fallbackValue = fallbackPreferences.string(forKey: key) {
            return fallbackValue
        }

        if !sawItemNotFound && !sawMissingEntitlement {
            error?.pointee = NSError(domain: NSOSStatusErrorDomain, code: Int(lastStatus))
        }
        return ""
    }

    func getStateStoreKeysJSON() -> String {
        var allItems: [[String: Any]] = []
        for keychainGroup in keychainGroups {
            let query = GoAppContext.withAccessGroup(keychainGroup, query: [
                kSecClass as String: kSecClassGenericPassword,
                kSecReturnAttributes as String: true,
                kSecMatchLimit as String: kSecMatchLimitAll,
            ])

            var result: AnyObject?
            let status = SecItemCopyMatching(query as CFDictionary, &result)
            if status == errSecSuccess, let items = result as? [[String: Any]] {
                allItems.append(contentsOf: items)
            }
        }

        let prefix = "statestore-"
        let keychainKeys = allItems.compactMap { $0[kSecAttrAccount as String] as? String }
        let fallbackKeys = fallbackPreferences.dictionaryRepresentation().keys
        let keys = Set(keychainKeys + Array(fallbackKeys))
            .filter { $0.hasPrefix(prefix) }
            .map { String($0.dropFirst(prefix.count)) }

        guard let data = try? JSONSerialization.data(withJSONObject: keys) else { return "[]" }
        return String(data: data, encoding: .utf8) ?? "[]"
    }

    // MARK: - Platform Info

    func getOSVersion(_ error: NSErrorPointer) -> String {
        let v = ProcessInfo.processInfo.operatingSystemVersion
        return "iOS \(v.majorVersion).\(v.minorVersion).\(v.patchVersion)"
    }

    func getDeviceName(_ error: NSErrorPointer) -> String {
        var size = 0
        sysctlbyname("hw.machine", nil, &size, nil, 0)
        var machine = [CChar](repeating: 0, count: size)
        sysctlbyname("hw.machine", &machine, &size, nil, 0)
        return String(cString: machine)
    }

    func getInstallSource() -> String {
        #if targetEnvironment(simulator)
        return "simulator"
        #else
        return "appstore"
        #endif
    }

    func shouldUseGoogleDNSFallback() -> Bool {
        return false
    }

    /// Go's (bool, error) return maps to ObjC BOOL output parameter + NSError**.
    func isChromeOS(_ ret0_: UnsafeMutablePointer<ObjCBool>?) throws {
        ret0_?.pointee = ObjCBool(false)
    }

    // MARK: - Network Interfaces

    func getInterfacesAsJson(_ error: NSErrorPointer) -> String {
        var addrs: UnsafeMutablePointer<ifaddrs>?
        guard getifaddrs(&addrs) == 0 else {
            return "[]"
        }
        defer { freeifaddrs(addrs) }

        // Collect interfaces and their addresses
        var ifaceMap: [String: (flags: UInt32, addrs: [[String: Any]])] = [:]
        var cursor = addrs
        while let ifa = cursor {
            let name = String(cString: ifa.pointee.ifa_name)
            let flags = ifa.pointee.ifa_flags

            if ifaceMap[name] == nil {
                ifaceMap[name] = (flags: flags, addrs: [])
            }

            if let sa = ifa.pointee.ifa_addr {
                let family = sa.pointee.sa_family
                if family == UInt8(AF_INET) {
                    sa.withMemoryRebound(to: sockaddr_in.self, capacity: 1) { sin in
                        var buf = [CChar](repeating: 0, count: Int(INET_ADDRSTRLEN))
                        var addr = sin.pointee.sin_addr
                        inet_ntop(AF_INET, &addr, &buf, socklen_t(INET_ADDRSTRLEN))
                        let ip = String(cString: buf)
                        var prefixLen = 32
                        if let netmask = ifa.pointee.ifa_netmask {
                            netmask.withMemoryRebound(to: sockaddr_in.self, capacity: 1) { nm in
                                let mask = UInt32(bigEndian: nm.pointee.sin_addr.s_addr)
                                prefixLen = mask.nonzeroBitCount
                            }
                        }
                        ifaceMap[name]?.addrs.append(["ip": ip, "prefixLen": prefixLen])
                    }
                } else if family == UInt8(AF_INET6) {
                    sa.withMemoryRebound(to: sockaddr_in6.self, capacity: 1) { sin6 in
                        var buf = [CChar](repeating: 0, count: Int(INET6_ADDRSTRLEN))
                        var addr = sin6.pointee.sin6_addr
                        inet_ntop(AF_INET6, &addr, &buf, socklen_t(INET6_ADDRSTRLEN))
                        var ip = String(cString: buf)
                        if sin6.pointee.sin6_scope_id != 0 {
                            ip += "%\(name)"
                        }
                        var prefixLen = 128
                        if let netmask = ifa.pointee.ifa_netmask {
                            netmask.withMemoryRebound(to: sockaddr_in6.self, capacity: 1) { nm in
                                let bytes = withUnsafeBytes(of: nm.pointee.sin6_addr) { Array($0) }
                                prefixLen = bytes.reduce(0) { $0 + $1.nonzeroBitCount }
                            }
                        }
                        ifaceMap[name]?.addrs.append(["ip": ip, "prefixLen": prefixLen])
                    }
                }
            }

            cursor = ifa.pointee.ifa_next
        }

        // Build JSON array
        var result: [[String: Any]] = []
        for (name, info) in ifaceMap {
            let idx = if_nametoindex(name)
            let iface: [String: Any] = [
                "name": name,
                "index": Int(idx),
                "mtu": 0, // MTU requires ioctl, skip for now
                "up": (info.flags & UInt32(IFF_UP)) != 0,
                "broadcast": (info.flags & UInt32(IFF_BROADCAST)) != 0,
                "loopback": (info.flags & UInt32(IFF_LOOPBACK)) != 0,
                "pointToPoint": (info.flags & UInt32(IFF_POINTOPOINT)) != 0,
                "multicast": (info.flags & UInt32(IFF_MULTICAST)) != 0,
                "addrs": info.addrs,
            ]
            result.append(iface)
        }

        do {
            let jsonData = try JSONSerialization.data(withJSONObject: result)
            return String(data: jsonData, encoding: .utf8) ?? "[]"
        } catch let err as NSError {
            error?.pointee = err
            return "[]"
        }
    }

    func getPlatformDNSConfig() -> String {
        // iOS Extension doesn't have easy access to system DNS config.
        // Return empty; the Go backend handles this gracefully.
        return ""
    }

    // MARK: - System Policy (MDM / Managed App Configuration)

    func getSyspolicyStringValue(_ key: String?, error: NSErrorPointer) -> String {
        guard let key = key else {
            error?.pointee = noSuchKeyError()
            return ""
        }
        let defaults = UserDefaults(suiteName: "com.apple.configuration.managed")
        guard let val = defaults?.string(forKey: key) else {
            error?.pointee = noSuchKeyError()
            return ""
        }
        return val
    }

    /// Go's (bool, error) return maps to ObjC BOOL output parameter + NSError**.
    func getSyspolicyBooleanValue(_ key: String?, ret0_: UnsafeMutablePointer<ObjCBool>?) throws {
        guard let key = key else { throw noSuchKeyError() }
        guard let defaults = UserDefaults(suiteName: "com.apple.configuration.managed"),
              defaults.object(forKey: key) != nil else { throw noSuchKeyError() }
        ret0_?.pointee = ObjCBool(defaults.bool(forKey: key))
    }

    func getSyspolicyStringArrayJSONValue(_ key: String?, error: NSErrorPointer) -> String {
        guard let key = key else {
            error?.pointee = noSuchKeyError()
            return "[]"
        }
        let defaults = UserDefaults(suiteName: "com.apple.configuration.managed")
        guard let arr = defaults?.array(forKey: key) as? [String] else {
            error?.pointee = noSuchKeyError()
            return "[]"
        }
        do {
            let data = try JSONSerialization.data(withJSONObject: arr)
            return String(data: data, encoding: .utf8) ?? "[]"
        } catch let err as NSError {
            error?.pointee = err
            return "[]"
        }
    }

    // MARK: - Hardware Attestation (Secure Enclave)
    
    /// Key storage for active Secure Enclave keys
    private static var loadedKeys: [String: SecKey] = [:]
    /// Lock for thread-safe access to loadedKeys
    private static let keysLock = NSLock()
    
    /// Thread-safe getter for loaded key
    private static func getLoadedKey(_ keyID: String) -> SecKey? {
        keysLock.lock()
        defer { keysLock.unlock() }
        return loadedKeys[keyID]
    }
    
    /// Thread-safe setter for loaded key
    private static func setLoadedKey(_ keyID: String, key: SecKey) {
        keysLock.lock()
        defer { keysLock.unlock() }
        loadedKeys[keyID] = key
    }
    
    /// Thread-safe removal of loaded key
    private static func removeLoadedKey(_ keyID: String) {
        keysLock.lock()
        defer { keysLock.unlock() }
        loadedKeys.removeValue(forKey: keyID)
    }
    
    /// Check if Secure Enclave is available on this device
    func hardwareAttestationKeySupported() -> Bool {
        // Check if device has Secure Enclave
        // Secure Enclave is available on devices with A7 chip or later (iPhone 5s+)
        var error: Unmanaged<CFError>?
        let flags: SecAccessControlCreateFlags = [.privateKeyUsage]
        guard let _ = SecAccessControlCreateWithFlags(
            kCFAllocatorDefault,
            kSecAttrAccessibleWhenUnlockedThisDeviceOnly,
            flags,
            &error
        ) else {
            return false
        }
        
        // Verify we can create Secure Enclave keys
        let testTag = "top.yesican.awgscale.se-test"
        let attributes: [String: Any] = [
            kSecAttrKeyType as String: kSecAttrKeyTypeECSECPrimeRandom,
            kSecAttrKeySizeInBits as String: 256,
            kSecAttrTokenID as String: kSecAttrTokenIDSecureEnclave,
            kSecPrivateKeyAttrs as String: [
                kSecAttrIsPermanent as String: false,
                kSecAttrApplicationTag as String: testTag.data(using: .utf8)!,
            ]
        ]
        
        var testError: Unmanaged<CFError>?
        if let testKey = SecKeyCreateRandomKey(attributes as CFDictionary, &testError) {
            // Clean up test key
            _ = testKey
            return true
        }
        
        return false
    }

    /// Create a new Secure Enclave key for hardware attestation
    func hardwareAttestationKeyCreate(_ error: NSErrorPointer) -> String {
        let keyID = UUID().uuidString
        let tag = "top.yesican.awgscale.attestation.\(keyID)"
        
        // Create access control for Secure Enclave
        var accessError: Unmanaged<CFError>?
        guard let accessControl = SecAccessControlCreateWithFlags(
            kCFAllocatorDefault,
            kSecAttrAccessibleWhenUnlockedThisDeviceOnly,
            [.privateKeyUsage],
            &accessError
        ) else {
            error?.pointee = accessError?.takeRetainedValue() as? NSError ?? 
                NSError(domain: "GoAppContext", code: -1,
                        userInfo: [NSLocalizedDescriptionKey: "Failed to create access control"])
            return ""
        }
        
        // Create key attributes for Secure Enclave ECDSA P-256
        let attributes: [String: Any] = [
            kSecAttrKeyType as String: kSecAttrKeyTypeECSECPrimeRandom,
            kSecAttrKeySizeInBits as String: 256,
            kSecAttrTokenID as String: kSecAttrTokenIDSecureEnclave,
            kSecPrivateKeyAttrs as String: [
                kSecAttrIsPermanent as String: true,
                kSecAttrApplicationTag as String: tag.data(using: .utf8)!,
                kSecAttrAccessControl as String: accessControl,
            ]
        ]
        
        var createError: Unmanaged<CFError>?
        guard let privateKey = SecKeyCreateRandomKey(attributes as CFDictionary, &createError) else {
            error?.pointee = createError?.takeRetainedValue() as? NSError ??
                NSError(domain: "GoAppContext", code: -1,
                        userInfo: [NSLocalizedDescriptionKey: "Failed to create Secure Enclave key"])
            return ""
        }
        
        // Store key reference (thread-safe)
        GoAppContext.setLoadedKey(keyID, key: privateKey)
        
        logger.log("Created Secure Enclave key: \(keyID, privacy: .public)")
        return keyID
    }

    /// Release a Secure Enclave key
    func hardwareAttestationKeyRelease(_ keyID: String?) throws {
        guard let keyID = keyID else { return }
        
        let tag = "top.yesican.awgscale.attestation.\(keyID)"
        
        // Remove from memory (thread-safe)
        GoAppContext.removeLoadedKey(keyID)
        
        // Delete from keychain
        let query: [String: Any] = [
            kSecClass as String: kSecClassKey,
            kSecAttrApplicationTag as String: tag.data(using: .utf8)!,
        ]
        
        let status = SecItemDelete(query as CFDictionary)
        if status != errSecSuccess && status != errSecItemNotFound {
            throw NSError(domain: NSOSStatusErrorDomain, code: Int(status))
        }
        
        logger.log("Released Secure Enclave key: \(keyID, privacy: .public)")
    }

    /// Get the public key for a Secure Enclave key
    func hardwareAttestationKeyPublic(_ keyID: String?) throws -> Data {
        guard let keyID = keyID else {
            throw NSError(domain: "GoAppContext", code: -1,
                          userInfo: [NSLocalizedDescriptionKey: "keyID is required"])
        }
        
        guard let privateKey = GoAppContext.getLoadedKey(keyID) else {
            // Try to load from keychain
            try hardwareAttestationKeyLoad(keyID)
            guard let loadedKey = GoAppContext.getLoadedKey(keyID) else {
                throw NSError(domain: "GoAppContext", code: -1,
                              userInfo: [NSLocalizedDescriptionKey: "Key not found: \(keyID)"])
            }
            return try getPublicKeyData(loadedKey)
        }
        
        return try getPublicKeyData(privateKey)
    }
    
    private func getPublicKeyData(_ privateKey: SecKey) throws -> Data {
        guard let publicKey = SecKeyCopyPublicKey(privateKey) else {
            throw NSError(domain: "GoAppContext", code: -1,
                          userInfo: [NSLocalizedDescriptionKey: "Failed to get public key"])
        }
        
        var error: Unmanaged<CFError>?
        guard let publicKeyData = SecKeyCopyExternalRepresentation(publicKey, &error) as Data? else {
            throw error?.takeRetainedValue() as? NSError ??
                NSError(domain: "GoAppContext", code: -1,
                        userInfo: [NSLocalizedDescriptionKey: "Failed to export public key"])
        }
        
        return publicKeyData
    }

    /// Sign data with a Secure Enclave key
    func hardwareAttestationKeySign(_ keyID: String?, data: Data?) throws -> Data {
        guard let keyID = keyID else {
            throw NSError(domain: "GoAppContext", code: -1,
                          userInfo: [NSLocalizedDescriptionKey: "keyID is required"])
        }
        
        guard let data = data, !data.isEmpty else {
            throw NSError(domain: "GoAppContext", code: -1,
                          userInfo: [NSLocalizedDescriptionKey: "data is required"])
        }
        
        guard let privateKey = GoAppContext.getLoadedKey(keyID) else {
            // Try to load from keychain
            try hardwareAttestationKeyLoad(keyID)
            guard let loadedKey = GoAppContext.getLoadedKey(keyID) else {
                throw NSError(domain: "GoAppContext", code: -1,
                              userInfo: [NSLocalizedDescriptionKey: "Key not found: \(keyID)"])
            }
            return try signData(loadedKey, data: data)
        }
        
        return try signData(privateKey, data: data)
    }
    
    private func signData(_ privateKey: SecKey, data: Data) throws -> Data {
        // Use ECDSA with SHA256
        let algorithm = SecKeyAlgorithm.ecdsaSignatureMessageX962SHA256
        
        guard SecKeyIsAlgorithmSupported(privateKey, .sign, algorithm) else {
            throw NSError(domain: "GoAppContext", code: -1,
                          userInfo: [NSLocalizedDescriptionKey: "Algorithm not supported"])
        }
        
        var error: Unmanaged<CFError>?
        guard let signature = SecKeyCreateSignature(privateKey, algorithm, data as CFData, &error) as Data? else {
            throw error?.takeRetainedValue() as? NSError ??
                NSError(domain: "GoAppContext", code: -1,
                        userInfo: [NSLocalizedDescriptionKey: "Signing failed"])
        }
        
        return signature
    }

    /// Load a Secure Enclave key from the keychain
    func hardwareAttestationKeyLoad(_ keyID: String?) throws {
        guard let keyID = keyID else {
            throw NSError(domain: "GoAppContext", code: -1,
                          userInfo: [NSLocalizedDescriptionKey: "keyID is required"])
        }
        
        // Check if already loaded
        if GoAppContext.getLoadedKey(keyID) != nil {
            return
        }
        
        let tag = "top.yesican.awgscale.attestation.\(keyID)"
        
        let query: [String: Any] = [
            kSecClass as String: kSecClassKey,
            kSecAttrApplicationTag as String: tag.data(using: .utf8)!,
            kSecAttrKeyType as String: kSecAttrKeyTypeECSECPrimeRandom,
            kSecReturnRef as String: true,
        ]
        
        var item: CFTypeRef?
        let status = SecItemCopyMatching(query as CFDictionary, &item)
        
        if status == errSecItemNotFound {
            throw NSError(domain: "GoAppContext", code: -1,
                          userInfo: [NSLocalizedDescriptionKey: "Key not found in keychain: \(keyID)"])
        }
        
        if status != errSecSuccess {
            throw NSError(domain: NSOSStatusErrorDomain, code: Int(status))
        }
        
        guard let cfItem = item else {
            throw NSError(domain: "GoAppContext", code: -1,
                          userInfo: [NSLocalizedDescriptionKey: "Failed to load key reference"])
        }
        
        // CFTypeRef -> SecKey (SecItemCopyMatching returns SecKey when kSecReturnRef is true)
        let privateKey = cfItem as! SecKey
        
        GoAppContext.setLoadedKey(keyID, key: privateKey)
        logger.log("Loaded Secure Enclave key: \(keyID, privacy: .public)")
    }

    // MARK: - Helpers

    private func noSuchKeyError() -> NSError {
        // Matches Go's syspolicy.ErrNoSuchKey error string so the Go side
        // can translate it back correctly.
        NSError(domain: "syspolicy", code: 0,
                userInfo: [NSLocalizedDescriptionKey: "no such key"])
    }
}

// MARK: - Go Notification Callback

/// Swift implementation of Go's NotificationCallback interface.
/// Receives JSON-serialized ipn.Notify payloads from Go's WatchNotifications.
class GoNotificationCallback: NSObject, LibtailscaleNotificationCallbackProtocol {
    private let handler: (Data) -> Void

    init(_ handler: @escaping (Data) -> Void) {
        self.handler = handler
    }

    func onNotify(_ payload: Data?) throws {
        guard let payload = payload else { return }
        handler(payload)
    }
}

// MARK: - Go InputStream from Data

/// Wraps Swift Data as a Go InputStream for passing request bodies to CallLocalAPI.
class DataInputStream: NSObject, LibtailscaleInputStreamProtocol {
    private var data: Data?

    init(_ data: Data) {
        self.data = data
    }

    func read() throws -> Data {
        guard let d = data else { return Data() }
        data = nil // consumed
        return d
    }

    func close() throws {
        data = nil
    }
}

#endif // canImport(Libtailscale)

func clearPersistedGoState() {
    #if canImport(Libtailscale)
    GoAppContext.clearPersistedState()
    #endif
}
